spring:
  application:
    name: parking-app-back
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/parking_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG